from __future__ import annotations

AI_CONCEPTS: dict[str, dict[str, str]] = {
    "2330.TW": {"theme": "AI 晶片製造", "role": "先進製程與 CoWoS 封裝核心"},
    "2454.TW": {"theme": "AI 晶片設計", "role": "高速運算與邊緣 AI 晶片"},
    "2303.TW": {"theme": "AI 晶片製造", "role": "晶圓代工與成熟製程支援"},
    "2379.TW": {"theme": "AI 晶片設計", "role": "高速傳輸與網通晶片"},
    "3034.TW": {"theme": "AI 晶片設計", "role": "高速介面與資料中心晶片"},
    "3661.TW": {"theme": "AI ASIC", "role": "客製化 ASIC 與高速運算"},
    "6669.TW": {"theme": "AI Server 散熱", "role": "資料中心散熱與伺服器零組件"},
    "2317.TW": {"theme": "AI Server 組裝", "role": "AI 伺服器與雲端資料中心製造"},
    "2382.TW": {"theme": "AI Server 組裝", "role": "AI 伺服器與雲端運算設備"},
    "3231.TW": {"theme": "AI Server 組裝", "role": "AI 伺服器與資料中心整機"},
    "2357.TW": {"theme": "AI PC / Edge AI", "role": "AI PC、伺服器與終端裝置"},
    "3017.TW": {"theme": "AI Server 散熱", "role": "散熱模組與資料中心熱管理"},
    "2327.TW": {"theme": "AI 電源 / 零組件", "role": "AI 伺服器被動元件與供電鏈"},
    "3711.TW": {"theme": "AI 半導體通路", "role": "半導體代理與 AI 供應鏈服務"},
    "NVDA": {"theme": "AI GPU", "role": "AI 加速器與 CUDA 生態核心"},
    "AMD": {"theme": "AI GPU", "role": "AI 加速器與資料中心 CPU/GPU"},
    "AVGO": {"theme": "AI ASIC / 網通", "role": "客製化 AI ASIC 與資料中心網通"},
    "MSFT": {"theme": "AI 雲端平台", "role": "Azure、Copilot 與企業 AI"},
    "GOOGL": {"theme": "AI 雲端平台", "role": "Gemini、TPU、Google Cloud"},
    "AMZN": {"theme": "AI 雲端平台", "role": "AWS AI 基礎設施與模型服務"},
    "META": {"theme": "AI 應用 / 模型", "role": "Llama、推薦系統與 AI 廣告"},
    "ORCL": {"theme": "AI 雲端平台", "role": "OCI AI 基礎設施"},
    "CRM": {"theme": "AI 軟體", "role": "企業 AI CRM 與 Agent 應用"},
    "ADBE": {"theme": "AI 軟體", "role": "生成式 AI 內容工具"},
    "AAPL": {"theme": "AI 終端裝置", "role": "裝置端 AI 與生態整合"},
    "INTC": {"theme": "AI 晶片", "role": "資料中心與邊緣 AI 晶片"},
}

MATERIAL_CONCEPTS: dict[str, dict[str, str]] = {
    "2383.TW": {"theme": "高速 CCL", "role": "AI server 高速板材，受益高速傳輸與高層板需求"},
    "6213.TW": {"theme": "高速 CCL", "role": "銅箔基板與高頻高速材料"},
    "6274.TWO": {"theme": "高速 CCL", "role": "高階 CCL，對應 AI server 與高速網通板"},
    "1815.TWO": {"theme": "玻纖布", "role": "CCL 上游玻纖布，受益高階板材用料升級"},
    "8358.TWO": {"theme": "銅箔", "role": "CCL 上游銅箔，連動高速板材與 PCB 需求"},
    "2368.TW": {"theme": "AI PCB", "role": "AI server 與高速運算 PCB"},
    "3037.TW": {"theme": "PCB / ABF", "role": "高階 PCB、IC 載板與 ABF 供應鏈"},
    "3044.TW": {"theme": "AI PCB", "role": "伺服器、車用與高階 PCB"},
    "8046.TW": {"theme": "ABF 載板", "role": "高階 IC 載板，連動 AI GPU/ASIC 封裝需求"},
    "3189.TW": {"theme": "IC 載板", "role": "IC 載板與先進封裝供應鏈"},
    "3017.TW": {"theme": "散熱材料 / 模組", "role": "AI server 散熱模組與熱管理"},
    "3324.TW": {"theme": "散熱材料 / 模組", "role": "液冷、散熱模組與資料中心熱管理"},
    "6669.TW": {"theme": "AI Server 整機", "role": "材料拉貨的下游需求觀察指標"},
    "3231.TW": {"theme": "AI Server 整機", "role": "伺服器整機，反映材料與零組件需求"},
    "2382.TW": {"theme": "AI Server 整機", "role": "AI server 出貨動能，影響上游材料拉貨"},
    "2330.TW": {"theme": "先進封裝材料", "role": "CoWoS 與先進製程需求的核心拉動者"},
    "3532.TW": {"theme": "矽晶圓", "role": "半導體上游矽晶圓"},
    "6488.TWO": {"theme": "矽晶圓", "role": "半導體上游矽晶圓"},
    "1560.TW": {"theme": "半導體耗材", "role": "再生晶圓、鑽石碟與製程耗材"},
    "3680.TW": {"theme": "半導體耗材", "role": "光罩盒、晶圓載具與 EUV 供應鏈"},
    "1303.TW": {"theme": "基礎化工材料", "role": "電子材料與塑化上游參考"},
    "1301.TW": {"theme": "基礎化工材料", "role": "塑化與化工材料上游參考"},
}
